/* A triangular number can also be generate by the formula
triangularNumber = n (n + 1) / 2
for any integer value of n. For example, the 10th triangular number, 55, can be generated by substituting q0 as the value for n in the preceding formula. write a program that generate a table of triangular numbers using the preceding formula. Have the program generate every fifty triangular number between 5 and 50 (that is, 5, 10, 15,....,50)
*/
#include <stdio.h>

int main(void)
{
    int n = 50;
    for (int i = 5; i <= n; i = i + 5)
    {
        printf("triangular number for %2i is %4d\n", i, (i * (i + 1) / 2));
    }

    return 0;
}